# Generated by Django 4.2.2 on 2023-06-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_Name', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Unit Name')),
                ('unit_Desc', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Unit Description')),
            ],
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('unit_Name',), name='unique_nameUnit'),
        ),
    ]
