# Generated by Django 4.2.2 on 2023-06-12 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_Number', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='WO Number')),
                ('pvm_Number', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Preventive Maintenance Number')),
                ('insp_Date', models.DateField(blank=True, null=True, verbose_name='Inspection Date')),
                ('nox', models.FloatField(blank=True, default=None, null=True, verbose_name='NOx')),
                ('nox_Remark', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='NOx Remark')),
                ('so2', models.FloatField(blank=True, default=None, null=True, verbose_name='SO2')),
                ('so2_Remark', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='SO2 Remark')),
                ('co2', models.FloatField(blank=True, default=None, null=True, verbose_name='CO2')),
                ('co2_Remark', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='CO2 Remark')),
                ('co', models.FloatField(blank=True, default=None, null=True, verbose_name='CO')),
                ('co_Remark', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='CO Remark')),
                ('o2', models.FloatField(blank=True, default=None, null=True, verbose_name='O2')),
                ('o2_Remark', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='O2 Remark')),
                ('dust', models.FloatField(blank=True, default=None, null=True, verbose_name='Dust')),
                ('dust_Remark', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Dust Remark')),
                ('crew_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Crew1', to=settings.AUTH_USER_MODEL)),
                ('crew_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Crew2', to=settings.AUTH_USER_MODEL)),
                ('crew_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Crew3', to=settings.AUTH_USER_MODEL)),
                ('pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PIC', to=settings.AUTH_USER_MODEL)),
                ('unit_Maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='preventivemaintenance',
            constraint=models.UniqueConstraint(fields=('wo_Number',), name='unique_woNumber'),
        ),
        migrations.AddConstraint(
            model_name='preventivemaintenance',
            constraint=models.UniqueConstraint(fields=('pvm_Number',), name='unique_pvmNumber'),
        ),
    ]
